version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network
    environment:
      DB_HOST: db
      DB_DATABASE: mango_store
      DB_USERNAME: root
      DB_PASSWORD: secret

  db:
    image: mysql:8.0
    container_name: mango_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mango_store
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - laravel_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysqldata:

networks:
  laravel_network:
    driver: bridge
